todo_list/core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('data/<int:pk>/', views.DataOverview.as_view(), name='dataoverview'),

    path('settings/', views.settings, name='settings'),
    path('settings/password/', views.password, name='password'),
    # path('', views.Analytics.as_view(), name="analytics"),
]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt # New library

from todo_list.schema import schema
from core.views import SignUpView, PrivateGraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name="signup"),

    path('', include('core.urls'), name="core"),
    path('api/', csrf_exempt(PrivateGraphQLView.as_view(graphiql=True)), name="api"),
]

todo_list/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ocupation = models.CharField(max_length=60, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserData.objects.create(user=instance)
    instance.userdata.save()

class Card(models.Model):
    IMPORTANCE_OPTIONS = (
        (1, 'low'),
        (2, 'normal'),
        (3, 'urgent'),
    )
    name = models.CharField(max_length=140)
    description = models.CharField(max_length=250, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    limit = models.DateTimeField(null=True, blank=True)

    finished = models.BooleanField(default=False)

    importance = models.IntegerField(choices=IMPORTANCE_OPTIONS, default=IMPORTANCE_OPTIONS[0][0])
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{} | {}".format(self.author, self.name)

todo_list/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    ocupation = forms.CharField(label="Ocupation", max_length=60, required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'ocupation', 'password1', 'password2', )

todo_list/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.utils.decorators import method_decorator
from django.views.generic.base import View

from django.http import JsonResponse
from .forms import SignUpForm
from .models import Card

from django.contrib.auth.mixins import LoginRequiredMixin
from graphene_django.views import GraphQLView

class PrivateGraphQLView(LoginRequiredMixin, GraphQLView):
    """Adds a login requirement to graphQL API access via main endpoint."""
    pass

class LoginRequiredView(View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class Index(LoginRequiredView):
    def get(self, request, *args, **kwargs):
        finishedCards = Card.objects.filter(author=request.user, finished=True)
        cards = Card.objects.filter(author=request.user, finished=False)
        return render(request, 'index.html', {
            'cards': cards,
            'finishedCards': finishedCards
        })        

class DataOverview(LoginRequiredView):
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            if 'from' not in request.GET or 'to' not in request.GET:
                return JsonResponse({
                    's': 1,
                    'm': 'Not valid request'
                })
            cards = Card.objects.filter(author=request.user,
                    created__range=[request.GET['from'], request.GET['to']])
        else:
            cards = Card.objects.filter(author=request.user)

        total_cards = cards.count()
        total_cards = 0.00000001 if total_cards == 0 else total_cards
        finished_percent = cards.filter(finished=True).count()
        unfinished_percent = cards.filter(finished=False).count()

        low_percent = cards.filter(importance=1).count()
        normal_percent = cards.filter(importance=2).count()
        urgent_percent = cards.filter(importance=3).count()

        ctx = {
            'total_cards': total_cards if total_cards >= 1 else 0,
            'finished_percent': finished_percent,
            'unfinished_percent': unfinished_percent,
            'low_percent': low_percent,
            'normal_percent': normal_percent,
            'urgent_percent': urgent_percent,
        }

        return JsonResponse({
            's': 0,
            'd': ctx
        }) if request.is_ajax() else \
        render(request, 'core/data_overview.html', ctx)

class Profile(LoginRequiredView):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/profile.html', {})

class SignUpView(View):
    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, 'registration/signup.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.userdata.ocupation = form.cleaned_data.get('ocupation')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('core:index')
        else:
            return render(request, 'registration/signup.html', {
                'form': form
            })

@login_required
def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        linkedin_login = user.social_auth.get(provider='linkedin')
    except UserSocialAuth.DoesNotExist:
        linkedin_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'core/settings.html', {
        'github_login': github_login,
        'linkedin_login': linkedin_login,
        'can_disconnect': can_disconnect
    })

@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'core/password.html', {'form': form})

todo_list/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="es">

<head>
   <title>{% block title %}Netica To-Do List{% endblock %}</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
</head>

<body>
   {% include 'navbar.html' %}
   <main>
      {% block content %}
      
      {% endblock %}
   </main>

   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
   {% block script_ %}

   {% endblock %}
</body>

</html>

todo_list/templates/core/data_overview.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container"></div>
      <h1 class="title">
        Data Overview
      </h1>
    </div>
  </div>
</section>
<br>
<br>
<section>
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
         <div class="field is-horizontal">
            <div class="field-body">
               <div class="field">
                  <p class="control is-expanded">
                     <input id="from" class="input" type="date">
                  </p>
               </div>
               <div class="field">
                  <p class="control is-expanded">
                     <input id="to" class="input" type="date">
                  </p>
               </div>
               <div class="field">
                  <p class="control">
                     <button id="filter" class="button is-info is-fullwidth">
                        Filter
                     </button>
                  </p>
               </div>
            </div>
         </div>
      </div>
    </div>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div class="container">
      <div class="columns">
          <div id="divChartBar" class="column is-6">
              <canvas id="chartBar"></canvas>
          </div>
          <div id="divChartPie" class="column is-6">
              <canvas id="chartPie"></canvas>
          </div>
      </div>
  </div>
</section>
{% endblock %}
{% block script_ %}
<script type="text/javascript">
   $(document).ready(function() {
      $("#from").val("");
      $("#to").val("");
      loadCharts();
      $("#filter").click(function() {
         if($("#from").val() && $("#to").val()) {
            filter($("#from").val(), $("#to").val());
         } else {
            loadCharts();
         } 
      }); 
   });

   function filter(f, t) {
      let data_ = {
         from: f,
         to: t
      }
      $.ajax({
         url: "{% url 'core:dataoverview' request.user.id %}",
         contentType: "application/json",
         type: 'GET',
         data: data_,
         success: function (result) {
            reloadCharts(result);
         },
         error: function (xhr, ajaxOptions, thrownError) {
            console.log(thrownError);
         }
      })
   }

   function loadCharts() {
      $("#chartBar").remove();
      $("#chartPie").remove();
      $("#divChartBar").html("<canvas id='chartBar'></canvas>");
      $("#divChartPie").html("<canvas id='chartPie'></canvas>");
      var ctx = document.getElementById("chartBar");
      var chartBar = new Chart(ctx, {
         type: 'bar',
         data: {
            labels: ["Low", "Normal", "Urgent"],
            datasets: [{
                  label: ["Total cards {{ total_cards }}"],
                  data: [{{low_percent}}, {{normal_percent}}, {{urgent_percent}}],
                  backgroundColor: [
                     'rgba(75, 192, 192, 0.8)',
                     'rgba(255, 206, 86, 0.8)',
                     'rgba(255, 99, 132, 0.8)',
                  ],
                  borderColor: [
                     'rgba(75, 192, 192, 1)',              
                     'rgba(255, 206, 86, 1)',
                     'rgba(255,99,132,1)',
                  ],
                  borderWidth: 1
            }]
         }
      });

      var ctx = document.getElementById("chartPie");
      var chartPie = new Chart(ctx, {
         type: 'doughnut',
         data: {
            datasets: [{
               data: [{{unfinished_percent}}, {{finished_percent}}],
               backgroundColor: [
                     'rgba(153, 102, 255, 0.8)',
                     'rgba(54, 162, 235, 0.8)',
               ],
               borderColor: [
                     'rgba(153, 102, 255, 1)', 
                     'rgba(54, 162, 235, 1)',          
               ],
               borderWidth: 1
            }],
            labels: [
               'Unfinished',
               'Finished'
            ]
         }
      });
   }

   function reloadCharts(data) {
      $("#chartBar").remove();
      $("#chartPie").remove();
      $("#divChartBar").html("<canvas id='chartBar'></canvas>");
      $("#divChartPie").html("<canvas id='chartPie'></canvas>");
      var ctx = document.getElementById("chartBar");
      var chartBar = new Chart(ctx, {
         type: 'bar',
         data: {
            labels: ["Low", "Normal", "Urgent"],
            datasets: [{
                  label: ["Total cards " + data.d.total_cards],
                  data: [data.d.low_percent, data.d.normal_percent, data.d.urgent_percent],
                  backgroundColor: [
                     'rgba(75, 192, 192, 0.8)',
                     'rgba(255, 206, 86, 0.8)',
                     'rgba(255, 99, 132, 0.8)',
                  ],
                  borderColor: [
                     'rgba(75, 192, 192, 1)',              
                     'rgba(255, 206, 86, 1)',
                     'rgba(255,99,132,1)',
                  ],
                  borderWidth: 1
            }]
         }
      });

      var ctx = document.getElementById("chartPie");
      var chartPie = new Chart(ctx, {
         type: 'doughnut',
         data: {
            datasets: [{
               data: [data.d.unfinished_percent, data.d.finished_percent],
               backgroundColor: [
                     'rgba(153, 102, 255, 0.8)',
                     'rgba(54, 162, 235, 0.8)',
                  ],
                  borderColor: [
                     'rgba(153, 102, 255, 1)', 
                     'rgba(54, 162, 235, 1)',          
                  ],
                  borderWidth: 1
            }],
            labels: [
               'Unfinished',
               'Finished'
            ]
         },
      });
   } 
</script>
{% endblock %}

todo_list/templates/core/password.html
{% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %

todo_list/templates/core/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<section class="hero is-info">
  <div class="hero-body">
    <div class="container"></div>
      <h1 class="title">
        Profile
      </h1>
    </div>
  </div>
</section>
<br>
<br>
<section>
  <div class="container">
    <div class="columns">
      <div class="column is-4 is-offset-4">
        <div class="field">
          <label class="label">Name</label>
          <p class="control has-icons-left">
            <input class="input" type="text" value="{{request.user.first_name}} {{request.user.last_name}}" readonly>
            <span class="icon is-small is-left">
              <i class="fas fa-address-card"></i>
            </span>
          </p>
        </div> 
        <div class="field">
          <label class="label">Email</label>
          <p class="control has-icons-left">
            <input class="input" type="email" value="{{request.user.email}}" readonly>
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
          </p>
        </div> 
        <div class="field">
          <label class="label">Username</label>
          <p class="control has-icons-left">
            <input class="input" type="text" value="{{request.user.username}}" readonly>
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
          </p>
        </div> 
        <div class="field">
          <label class="label">Ocupation</label>
          <p class="control has-icons-left">
            <input class="input" type="text" value="{{request.user.userdata.ocupation}}" readonly>
            <span class="icon is-small is-left">
              <i class="fas fa-building"></i>
            </span>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

todo_list/templates/core/settings.html
{% extends 'base.html' %}

{% block content %}
  <h2>Settings</h2>
  <h3>GitHub</h3>
  {% if github_login %}
    <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">{{ github_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'github' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from GitHub</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from GitHub</button>
      <p style="color: red">You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Github.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
  {% endif %}
{% endblock %}

todo_list/templates/graphene/graphiql.html
<!--
The request to this GraphQL server provided the header "Accept: text/html"
and as a result has been presented GraphiQL - an in-browser IDE for
exploring GraphQL.
If you wish to receive JSON, provide the header "Accept: application/json" or
add "&raw" to the end of the URL within a browser.
-->
<!DOCTYPE html>
<html>
<head>
  <style>
    html, body {
      height: 100%;
      margin: 0;
      overflow: hidden;
      width: 100%;
    }
  </style>
  <link href="//cdn.jsdelivr.net/npm/graphiql@{{graphiql_version}}/graphiql.css" rel="stylesheet" />
  <script src="//cdn.jsdelivr.net/npm/whatwg-fetch@2.0.3/fetch.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/react@16.2.0/umd/react.production.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/react-dom@16.2.0/umd/react-dom.production.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/graphiql@{{graphiql_version}}/graphiql.min.js"></script>
</head>
<body>
  <script>
    // Parse the cookie value for a CSRF token
    var csrftoken;
    var cookies = ('; ' + document.cookie).split('; csrftoken=');
    if (cookies.length == 2)
      csrftoken = cookies.pop().split(';').shift();

    // Collect the URL parameters
    var parameters = {};
    window.location.search.substr(1).split('&').forEach(function (entry) {
      var eq = entry.indexOf('=');
      if (eq >= 0) {
        parameters[decodeURIComponent(entry.slice(0, eq))] =
          decodeURIComponent(entry.slice(eq + 1));
      }
    });
    // Produce a Location query string from a parameter object.
    function locationQuery(params) {
      return '?' + Object.keys(params).map(function (key) {
        return encodeURIComponent(key) + '=' +
          encodeURIComponent(params[key]);
      }).join('&');
    }
    // Derive a fetch URL from the current URL, sans the GraphQL parameters.
    var graphqlParamNames = {
      query: true,
      variables: true,
      operationName: true
    };
    var otherParams = {};
    for (var k in parameters) {
      if (parameters.hasOwnProperty(k) && graphqlParamNames[k] !== true) {
        otherParams[k] = parameters[k];
      }
    }
    var fetchURL = locationQuery(otherParams);
    // Defines a GraphQL fetcher using the fetch API.
    function graphQLFetcher(graphQLParams) {
      var headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      };
      if (csrftoken) {
        headers['X-CSRFToken'] = csrftoken;
      }
      return fetch(fetchURL, {
        method: 'post',
        headers: headers,
        body: JSON.stringify(graphQLParams),
        credentials: 'include',
      }).then(function (response) {
        return response.text();
      }).then(function (responseBody) {
        try {
          return JSON.parse(responseBody);
        } catch (error) {
          return responseBody;
        }
      });
    }
    // When the query and variables string is edited, update the URL bar so
    // that it can be easily shared.
    function onEditQuery(newQuery) {
      parameters.query = newQuery;
      updateURL();
    }
    function onEditVariables(newVariables) {
      parameters.variables = newVariables;
      updateURL();
    }
    function onEditOperationName(newOperationName) {
      parameters.operationName = newOperationName;
      updateURL();
    }
    function updateURL() {
      history.replaceState(null, null, locationQuery(parameters));
    }
    // Render <GraphiQL /> into the body.
    ReactDOM.render(
      React.createElement(GraphiQL, {
        fetcher: graphQLFetcher,
        onEditQuery: onEditQuery,
        onEditVariables: onEditVariables,
        onEditOperationName: onEditOperationName,
        query: '{{ query|escapejs }}',
        response: '{{ result|escapejs }}',
        {% if variables %}
        variables: '{{ variables|escapejs }}',
        {% endif %}
        {% if operation_name %}
        operationName: '{{ operation_name|escapejs }}',
        {% endif %}
      }),
      document.body
    );
  </script>
</body>
</html>

todo_list/templates/navbar.html
{% load static %}

<style>
   a.navbar-item:hover {
      color: #1496ed !important;
   }

   p.username:hover {
      cursor: default;
   }
</style>
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
   <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'core:index' %}">
         <img src="{% static 'img/check.png' %}" width="38" height="38">
      </a>
      <p class="navbar-item username">Hi {{ request.user.username }}</p>
      <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
         <span aria-hidden="true"></span>
         <span aria-hidden="true"></span>
         <span aria-hidden="true"></span>
      </a>
   </div>
   <div class="navbar-menu is-black" id="navMenu">
      <div class="navbar-start">
         <a class="navbar-item" href="{% url 'core:index' %}">
            Home
         </a>
         <a class="navbar-item" href="{% url 'core:profile' request.user.id %}">
            My profile
         </a>
         <a class="navbar-item" href="{% url 'core:dataoverview' request.user.id %}">
            Data Overview
         </a>
      </div>
      <div class="navbar-end">
         <div class="navbar-item">
            <div class="buttons">
               <a class="button is-info" href="{% url 'logout' %}">Logout&nbsp;&nbsp;<i class="fas fa-sign-out-alt"></i></a>
            </div>
         </div>
      </div>
   </div>
</nav>

{% block script_ %}
   <script>
      document.addEventListener('DOMContentLoaded', () => {
         // Get all "navbar-burger" elements
         const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
         // Check if there are any navbar burgers
         if ($navbarBurgers.length > 0) {
            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
               el.addEventListener('click', () => {
                  // Get the target from the "data-target" attribute
                  const target = el.dataset.target;
                  const $target = document.getElementById(target);
                  // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                  el.classList.toggle('is-active');
                  $target.classList.toggle('is-active');
               });
            });
         }
      });
   </script>
{% endblock %}

todo_list/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Document</title>
   <style>
      html {
         width: 100%;
         height: 100%;
      }
   </style>
</head>
<body>
   <div style="width: 100%; height: 100%;">
      hello world
   </div>
</body>
</html>